"""
export.py
---------
Builds downloadable CSV, JSON, and Markdown exports from the current
meeting's data. Pure functions only — no Streamlit calls here, so this
module stays easy to unit-test.
"""

from __future__ import annotations

import json
from datetime import date, datetime
from typing import Any

import pandas as pd


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    export_cols = [c for c in df.columns if c != "ID"]
    return df[export_cols].to_csv(index=False).encode("utf-8")


def to_json_bytes(
    meeting_title: str,
    meeting_date: str,
    team_project: str,
    participants: str,
    summary: str,
    decisions: list[str],
    df: pd.DataFrame,
    risks: list[str],
    follow_ups: list[str],
) -> bytes:
    export_cols = [c for c in df.columns if c != "ID"]
    payload: dict[str, Any] = {
        "meeting_title": meeting_title,
        "meeting_date": meeting_date,
        "team_project": team_project,
        "participants": participants,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "meeting_summary": summary,
        "key_decisions": decisions,
        "action_items": df[export_cols].to_dict(orient="records") if not df.empty else [],
        "risks_and_blockers": risks,
        "follow_up_questions": follow_ups,
    }
    return json.dumps(payload, indent=2).encode("utf-8")


def to_markdown_report(
    meeting_title: str,
    meeting_date: str,
    team_project: str,
    participants: str,
    summary: str,
    decisions: list[str],
    df: pd.DataFrame,
    risks: list[str],
    follow_ups: list[str],
) -> bytes:
    lines: list[str] = []
    lines.append(f"# Meeting Report — {meeting_title or 'Untitled Meeting'}")
    lines.append("")
    lines.append(f"**Date:** {meeting_date or 'Not specified'}  ")
    lines.append(f"**Team / Project:** {team_project or 'Not specified'}  ")
    lines.append(f"**Participants:** {participants or 'Not specified'}  ")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(summary or "_No summary available._")
    lines.append("")
    lines.append("## Key Decisions")
    lines.append("")
    if decisions:
        lines.extend(f"- {d}" for d in decisions)
    else:
        lines.append("_No decisions recorded._")
    lines.append("")
    lines.append("## Action Items")
    lines.append("")
    if not df.empty:
        lines.append("| Task | Owner | Deadline | Priority | Status | Dependency |")
        lines.append("|---|---|---|---|---|---|")
        for _, row in df.iterrows():
            task = str(row["Task"]).replace("|", "\\|")
            owner = str(row["Owner"]).replace("|", "\\|")
            deadline = str(row["Deadline"]).replace("|", "\\|")
            priority = str(row["Priority"]).replace("|", "\\|")
            status = str(row["Status"]).replace("|", "\\|")
            dependency = str(row["Dependency"]).replace("|", "\\|")
            lines.append(f"| {task} | {owner} | {deadline} | {priority} | {status} | {dependency} |")
    else:
        lines.append("_No action items extracted._")
    lines.append("")
    lines.append("## Risks / Blockers")
    lines.append("")
    if risks:
        lines.extend(f"- {r}" for r in risks)
    else:
        lines.append("_No risks or blockers recorded._")
    lines.append("")
    lines.append("## Follow-up Questions")
    lines.append("")
    if follow_ups:
        lines.extend(f"- {q}" for q in follow_ups)
    else:
        lines.append("_No open follow-up questions._")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by MeetMind AI — Turn messy meetings into organized action._")

    return "\n".join(lines).encode("utf-8")


def to_text_report(*args, **kwargs):
    return to_markdown_report(*args, **kwargs).decode("utf-8").replace("# ","").replace("## ","").replace("**","").encode("utf-8")
